### ISSUE TITLE
[CONSOLE] User avatar issues on project members page

### ISSUE THREAD

**Issue by sternhenri** [gretelai/support#2]
**Is this a bug or a Feature Request (FR) ?**

bug (2)

**What would you like to see changed, enhanced, or fixed?**

- User avatars don't initially load when using Ghostery
- User avatars have a weird blur on Safari.

**What browser and version are you using?**

84.0.1 (64-bit) with Ghostery.
Safari 14.0.1 for blur.

**Are there console errors? Can you provide snippets?**

None

**Do you have any screenshots you can provide?**

black boxes my own
<img width="1230" alt="Gretel" src="https://user-images.githubusercontent.com/3359083/103801687-5f365700-504e-11eb-92fe-96d327160e63.png">

**Comment by johntmyers** [comment]
Thanks, we'll take a look and see. We've had a decent amount of issues with Safari. It'd not ideal, but FF/Chrome will give you a little more mileage as we work through these issues.

**Comment by johntmyers** [comment]
Closing as we are currently working on our newly updated console for our Beta2 launch.
